config/routes.rb
Rails.application.routes.draw do
  get "welcome/index"
  get "welcome/about"
  resources :signers

  root to: 'welcome#index'
  
end

app/models/signer.rb
class Signer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/signers_controller.rb
class SignersController < ApplicationController
  before_action :set_signer, only: [:show, :edit, :update, :destroy]

  # GET /signers
  # GET /signers.json
  def index
    @signers = Signer.all
  end

  # GET /signers/1
  # GET /signers/1.json
  def show
  end

  # GET /signers/new
  def new
    @signer = Signer.new
  end

  # GET /signers/1/edit
  def edit
  end

  # POST /signers
  # POST /signers.json
  def create
    @signer = Signer.new(signer_params)

    respond_to do |format|
      if @signer.save
        format.html { redirect_to @signer, notice: 'Signer was successfully created.' }
        format.json { render :show, status: :created, location: @signer }
      else
        format.html { render :new }
        format.json { render json: @signer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signers/1
  # PATCH/PUT /signers/1.json
  def update
    respond_to do |format|
      if @signer.update(signer_params)
        format.html { redirect_to @signer, notice: 'Signer was successfully updated.' }
        format.json { render :show, status: :ok, location: @signer }
      else
        format.html { render :edit }
        format.json { render json: @signer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signers/1
  # DELETE /signers/1.json
  def destroy
    @signer.destroy
    respond_to do |format|
      format.html { redirect_to signers_url, notice: 'Signer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_signer
      @signer = Signer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def signer_params
      params.require(:signer).permit(:name, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signers_helper.rb
module SignersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Signerdemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <ul class="nav nav-tabs">
    <%= link_to "Home", root_path %>
    <%= link_to "Signers", signers_path %>
    <%= link_to "About", welcome_about_path %>
  </ul>
  
  <%= yield %>
</div>
  
</body>
</html>

app/views/signers/_form.html.erb
<%= form_for(@signer) do |f| %>
  <% if @signer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@signer.errors.count, "error") %> prohibited this signer from being saved:</h2>

      <ul>
      <% @signer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/signers/edit.html.erb
<h1>Editing signer</h1>

<%= render 'form' %>

<%= link_to 'Show', @signer %> |
<%= link_to 'Back', signers_path %>

app/views/signers/index.html.erb
<h1>Listing signers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @signers.each do |signer| %>
      <tr>
        <td><%= signer.name %></td>
        <td><%= signer.email %></td>
        <td><%= link_to 'Show', signer %></td>
        <td><%= link_to 'Edit', edit_signer_path(signer) %></td>
        <td><%= link_to 'Destroy', signer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Signer', new_signer_path %>

app/views/signers/new.html.erb
<h1>New signer</h1>

<%= render 'form' %>

<%= link_to 'Back', signers_path %>

app/views/signers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @signer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @signer.email %>
</p>

<%= link_to 'Edit', edit_signer_path(@signer) %> |
<%= link_to 'Back', signers_path %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>